name: 'run Venom'
description: ''
inputs:
  workingDirectory:
    description: "The working directory of your application"
    default: ""
  artifactName:
    description: "The name of artifact, if empty the system will not artifact the venom results"
    default: ""
  venom_release:
    description: "The url of venom release"
    default: https://github.com/ovh/venom/releases/download/v0.27.0/venom.linux-amd64
  venom_path:
    desciption: "The path of venom test to execute"
    required: true
  venom_parallel:
    description: "Number of test to execute in parallel"
    default: 1
  venom_outputdir:
    description: "Output directory to store results"
    default: "."
  venom_log:
    description: "Venom logging level"
    default: warn
  venom_environment:
    description: "Venom environment variables"
    default: ""
  venom_variable:
    description: "Venom variables"
    default: ""
  venom_exclude:
    description: "Exclude some tests"
    default: ""
  venom_format:
    description: "Venom format: yaml, json, xml, tap"
    default: xml
  venomStopOnFailure:
    description: "Flag to indicate to venom to stop test suite when a test case fail"
    default: false
  venomStrict:
    description: "Flag to indicate to venom to exit when a test fail"
runs:
  using: 'node12'
  main: 'index.js'
